name: Update AdGuard list
on:
  push:
    paths:
      - 'pihole-google.txt'
jobs:
  update:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
      name: Python setup
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Run Python script
      run: |
        python adguard.py
    - name: Commit AdGuard list
      run: |
        git config --global user.name 'Nick Spaargaren'
        git config --global user.email 'nickspaargaren@users.noreply.github.com'
        git pull origin ${GITHUB_REF##*/}
        git commit -am "Automated AdGuard list update"
        git push